#store routes
    
hecommerce_store_buy:
    path: /store/buy
    defaults:  { _controller: HeadooEcommerceBundle:Store:buy }
    methods:  [GET]

#id = Service Id  
hecommerce_store_cart:
    path: /store/cart/{id}
    defaults:  { _controller: HeadooEcommerceBundle:Store:cart }
    methods:  [GET, POST]
    requirements:
        id:  \d+
        
hecommerce_store_summary:
    path: /store/summary
    defaults:  { _controller: HeadooEcommerceBundle:Store:summary }
    methods:  [GET]
    
hecommerce_store_payment:
    path: /store/payment
    defaults:  { _controller: HeadooEcommerceBundle:Store:payment }
    methods:  [GET]

    
